### ISSUE TITLE
RFC 7405

### ISSUE THREAD

**Issue by ezzatron** [ldthomas/apg-js2#1]
I was just having a quick play around with APG, and I'm getting errors for case-sensitive literal text strings introduced in [RFC 7405](https://tools.ietf.org/html/rfc7405#section-2.1) (which updates [RFC 5234](https://tools.ietf.org/html/rfc5234)). For example:

```
keyword = %s"array" / %s"bool"
```

Results in `Unrecognized SABNF element.` for both instances of `%s`.

In addition, RFC 5234 is [case **insensitive**](https://tools.ietf.org/html/rfc5234#section-2.3), and the parsers that APG currently generates do not _seem_ to be honoring this (I say this from looking at the generated parser, and only seeing ASCII values for exact case matches):

> ABNF strings are case insensitive and the character set for these strings is US-ASCII.
> 
> Hence:
> 
>    rulename = "abc"
> 
> and:
> 
>    rulename = "aBc"
> 
> will match "abc", "Abc", "aBc", "abC", "ABc", "aBC", "AbC", and "ABC".

**Comment by ldthomas** [comment]
Thanks for pointing out RFC 7405 to me. I was unaware of the update to RFC 5234. I'll try to get a version 2.1.x update out sometime that honors the `%i, %s` syntax. Can't say when right now. However, you can match case-sensitive strings with this version using single quotes instead of double. For example:

```
insensitive = "abc"
sensitive =  'ABC'
```

The first rule would match both `abc` and `ABC`. The second would only match `ABC`.

APG v2.0 attempts to correctly parse strict RFC 5234 grammars with the addition of some extra features (superset ABNF). One of those extra features is the single-quoted, case-sensitive strings. I see that I missed that feature in the README file, but if you look at the `resources/ABNFforSABNF.bnf` file it is listed there.

It is true that the grammar object only saves the lower case characters for case-insensitive strings, but the TLS operator in the parser library converts all the input strings it attempts to match to lower case before matching. Build an actual parser for the grammar:

```
rulename = "abc" *("," "abc")
```

(you can do this with some simple changes to [apg-js2-examples](https://github.com/ldthomas/apg-js2-examples) `simple/setup.js`) and you will see that it correctly parses:

```
abc,Abc,aBc,abC,ABc,aBC,AbC,ABC

```

Turn on tracing with the filter set as so:

```
parser.trace.filter.operators["tls"] = true;
```

and you can see the TLS matches explicitly.

**Comment by ezzatron** [comment]
Ah okay, that makes sense. Thanks!

**Comment by ldthomas** [comment]
OK, and thanks for the RFC 7405 heads up.
