### ISSUE TITLE
Verbosity level?

### ISSUE THREAD

**Issue by do-** [ldthomas/apg-js2#8]
Hi Lowell,

Having downloaded http://docs.oasis-open.org/odata/odata/v4.01/cs01/abnf/odata-abnf-construction-rules.txt and launched

 apg -i odata-abnf-construction-rules.txt

some tens of minutes ago, I still watch my CPU at 100% with zero bytes output.

Is there a way to obtain some sort of real time debug print just to guess if it worth waiting? The `-v` command line switch gives the version number and I didn't find any key to verbose mode.

Thank you in advance.

**Comment by ldthomas** [comment]
Yeah, there is a problem with apg-js2 and very large grammars. The attributes algorithm is different than the Java version and chokes on very large grammars. Just comment out lines 114-118 in apg.js. This will bypass the attributes calculation. It’s a little dangerous with a new grammar, since you don’t know if you might have some attribute errors. But the OData grammar is good and I think you will get a good parser without the attributes. I’d fix it but I’m swamped with other projects right now. Maybe someday ...

**Comment by ldthomas** [comment]
Hope this worked for you.
